x=list(range(8))
print(x)
x=list(range(5))
print(x)
name=["ali","ana","mina","sara"]
number=list(range(4))
name.append(number)
print(name)
library=["small","big","school","university"]
a=list(range(6))
library.append(a)
print(library)
a=[1,2,3,4]
b=[5,6,7]
a.extend(b)
print(a)
num1=[2,4,6]
num2=[1,3,5]
num1.extend(num2)
print(num1)
medal=["gold","silver"]
number=[7,8,9]
medal.extend(number)
print(medal)
room=["small","big","brown"]
student=["ali","sara","zahra"]
room.extend(student)
print(room)
x=["doctor","num","digit"]
b=list(range(5))
x.extend(b)
print(x)
animal=["dog","cat"]
animal.insert(0,"pet")
print(animal)
score=[20,30,40,50]
score.insert(1,60)
print(score)
weather=["rainy","cloudy","snowy","hot"]
weather.insert(2,"teacher")
print(weather)
city=["arak","tehran","tabriz","shiraz"]
city.insert(2,"paris")
print(city)
car=["toyota","bmw","tesla"]
car.insert(2,"honda")
print(car)
phone=["samsung","nokia","sony","lg"]
phone.insert(0,"a70")
print(phone)
game=["chess","football","tennis"]
game.insert(1,"basketball")
print(game)
activity=["swim","run","walk"]
activity.insert(0,"yoga")
print(activity)
drink=["water","tea"]
drink.insert(0,"milk")
print(drink)
x=["s","h","j","w"]
x.pop()
print(x)
number=[2,4,8,9,0]
number.pop()
print(number)
fat=["boy","girl","man","woman"]
fat.pop()
print(fat)
short=["film","distance","dress","story"]
short.pop()
print(short)
long=["hair","dress","trip","story"]
long.pop()
print(long)
average=[18,14,20,19]
average.remove(14)
print(average)
year=[2020,2022,2025,1998]
year.remove(2020)
print(year)
place=["room","home","park","market","forest","school"]
place.remove("home")
print(place)
ball=["basketball","football","golf","wight"]
ball.remove("golf")
print(ball)
group=["math","python","physic","students","teachers","family","friends"]
group.remove("family")
print(group)
fix=["car","phone","door","window","bike"]
fix.remove("car")
print(fix)
window=["glass","wood","small","big"]
window.remove("glass")
print(window)
cup=["tea","milk","water"]
cup.remove("tea")
print(cup)
bowl=["copper","glass","plastic","small","big"]
bowl.remove("copper")
print(bowl)
blue=["sky","car","pen","shirt"]
blue.reverse()
print(blue)
market=["fruits","meat","clothes"]
market.reverse()
print(market)
count=[1,5,6,8,10]
count.reverse()
print(count)
figure=[1,6,9,5]
figure.reverse()
print(figure)
red=["apple","blood","tomato","shirt","hat","car"]
red.reverse()
print(red)
white=["flower","shirt","milk","paper","snow"]
white.reverse()
print(white)
num=[4,9,10,54,32]
num.sort()
print(num)
fruit=["orange","banana","apple"]
fruit.sort()
print(fruit)
city=["tehran","shiraz","arak","paris"]
city.sort()
print(city)
beautiful=["city","flower","forest","film","boy"]
beautiful.sort()
print(beautiful)
glass=["cup","bottle","jar"]
glass.sort()
print(glass)
figure=(1,4,6,8)
print(figure)
print(type(figure))
product=("apple","banana","orange")
print(product)
print(type(product))
score=(10,5,6,20)
print(score*3)
price=(40,80,800)
print(price*2)
num=(1,4,8,5)
print(num*4)
digit=(2,4,8)
print(digit*5)
fair=("flover","car","book")
print(fair*2)
x=()
print(x)
number=()
print(number)
word=()
print(word)
message=()
print(message)
empty=("empty room","empty box","empty plate")
print(empty)
print(type(empty))
nature=("river","forest","lake","see")
print(nature)
print(type(nature))
a=("cat","car",3,5,8,True,False)
print(a)
print(type(a))
d=("word","toyota","silver",8,6,20,True,False)
print(d)
print(type(d))
speed=(30,40,60)
print(speed)
print(type(speed))
a=(1,6,8)
b=(80,23,20)
print(a+b)
x=(2,9,10)
y=(29,30)
result=x+y
print(result)
carton=("small carton","large carton","brown carton","fruit carton")
a=(1,4,8)
print(carton+a)
tropical=("pineapple","papaya","kiwi","banana","mango")
figure=(5,8,90,80)
result=tropical+figure
print(result)
problem=("math problem","physic problem","python problem","easy problem","hard problem")
teach=("math","chess","python","english")
print(problem+teach)
festival=("spring","flover","music","art","food","film","summer")
poster=("photo","text","colorful","large","image","actor")
print(festival+poster)
lesson=("easy","hard","short","english","math")
photo=("nature","flower","animals","car","toyota")
print(lesson+photo)
end=("book","film","football","game","day","year","lesson")
vitamin=("A","B","C","D")
print(end+vitamin)
skill=("programming","design","cook","driving","writing","chess")
fast=("car","train","runner")
print(fast+skill)
decimal=(1.9,4.5,6.7,8.9)
print(decimal)
print(type(decimal))
decimal_number=(1.5,6.9,4.8)
whole_number=(2,5,7,8)
print(decimal_number+whole_number)
vehicle=("car","bike","bus","train")
tool=("hammer","wrench","drill","saw","knife")
print(vehicle+tool)
c=list(range(10))
print(c)
a=range(10)
print(a)
x=list(range(2))
print(x)
digit=[1,2,3]
digit.append(5)
print(digit)
decimal=[1.7,3.9,6.5]
decimal.append("doctor")
print(decimal)
new=["new book","new movie","new friend","new car"]
list=[1,7,"cat"]
new.append(list)
print(new)
old=["old book","old car","old house","old photo"]
next=["next day","next week","next year","goal next"]
old.append(next)
print(old)
coach=["life coach","football coach","chess coach","basketball coach"]
coach.append("tennis coach")
print(coach)
even_number=[2,4,6,8]
even_number.extend([10,12])
print(even_number)
x=[2,4,6,8]
y=[1,3,5]
x.extend(y)
print(x)
odd_number=[5,9,11,13]
odd_number.append(15)
print(odd_number)
news=["sport news","economic news","daily news","short news"]
news.append("science news")
print(news)
send=["photo","video","message"]
send.append("file")
print(send)
video=["python video","math video"]
video.extend(["short video","english video"])
print(video)
text=["sentence","paragraph"]
list=["message","note"]
text.extend(list)
print(text)


