x=("ball","copper",6,True)
print(x)
car=("toyota","tesla",1,2,True)
print(car)
x=("ali","reza","mina","mahsa")
print(x[0])
print(x[1])
print(x[3])
print(x[:])
print(x[2:3])
print(x[1:3])
print(x[-1])
print(x[-2])
num=(1,2,3,9,7,5,10,19)
print(num[1:4])
print(num[2:6])
print(num[3:5])
print(num[-1:-3])
print(num[-2:-5])
print(num[-5])
metal=("gold","silver","copper")
print("ali" in metal)
print("gold" in metal)
print("silver" not in metal)
print("copper" in metal)
company=("sony","google","samsung","panasonic")
print("sony" in company)
print("teacher" in company)
print("google" not in company)
print("samsung" in company)
print("red" in company)
tropical=("mango","kiwi","papaya","banana")
print("mango" in tropical)
print("car" in tropical)
print("kiwi" not in tropical)
print("banana" in tropical)
print("room" in tropical)
tv=("samsung","sony","led tv","lg")
print(len(tv))
number=(1,3,6,9)
print(len(number))
score=(10,16,18,20,19)
print(len(score))
speed=(50,40,60,100,120)
print(len(speed))
car=("toyota","benz","tesla")
print(len(car))
color=("red","green","brown","black")
print(len(color))
num=(1,40,65,76)
print(max(num))
decimal=(1.7,6.7,5.8,8.9,3.8)
print(max(decimal))
float1=(4.6,7.8,3.5,9.7)
print(max(float1))
average=(18,19,20,14,13)
print(max(average))
count=(20,40,80,100)
print(max(count))
digit=(2,6,3,9)
print(min(digit))
figure=(4,8,9,6,3,1)
print(min(figure))
x="word"
z=tuple(x)
print(z)
text="hello ali"
x=tuple(text)
print(x)
word="math"
a=tuple(word)
print(a)
word="hard"
c=tuple(word)
print(c)
sentence="I love you"
a=tuple(sentence)
print(a)
fruit="apple"
x=tuple(fruit)
print(x)
x="easy"
s=tuple(x)
print(s)
a="number"
b=tuple(a)
print(b)
a="decimal"
c=tuple(a)
print(c)
text="I am learning python"
a=tuple(text)
print(a)
b=tuple(range(5))
print(b)
b=tuple(range(7))
print(b)
x=tuple(range(4))
print(x)
a=tuple(range(10))
print(a)
c=tuple(range(4))
print(c)
d=tuple(range(3))
print(d)
send=("message","file","file","video","photo")
print(send.count("file"))
x=("a","f","c","c","c")
print(x.count("c"))
number=(3,8,8,8,23,90)
print(number.count(8))
price=(50,80,74,80,20)
print(price.count(80))
city=("arak","tehran","shiraz","paris")
print(city.count("arak"))
country=("iran","iran","germany")
print(country.count("iran"))
animal=("cat","cat","dog","cat")
print(animal.count("cat"))
ticket=("bus","metro","bus","bus","train")
print(ticket.count("bus"))
play=("football","chess","basketball","chess","chess")
print(play.count("chess"))
coach=("football","tennis")
print(coach.count("football"))
library=("central","school","university","small","big")
print(library[0])
print(library[:])
print(library[-2])
print(library[0:-2])
print(library[-1])
year=(2020,2022,2025,2021)
print(2020 in year)
print(1998 in year)
print(2021 in year)
print(2025 not in year)
text="I am from arak"
print("I" in text)
print("i" in text)
print("am" not in text)
print("to" not in text)
print("arak" in text)
word="medium"
print("M" in word)
print("medium" in word)
print("i" in word)
x=("wood","metal","liquid")
print(len(x))
age=(10,7,25,87)
print(len(age))
medal=('gold',"silver")
print(len(medal))
blood_type=("a","b","AB","o")
print(len(blood_type))
group=("music","python","family")
print(len(group))
size=("small","big","medium","xl","large")
print(len(size))
tropical_fruit=("banana","kiwi","papaya")
print(max(tropical_fruit))
book=("story","novel","math","history")
print(max(book))
x="big"
b=tuple(x)
print(b)
a="lamp"
c=tuple(a)
print(c)
tree="pineapple"
c=tuple(tree)
print(c)
figure=(3,8,6,20)
print(max(figure))
print(min(figure))
x=(4,6,9,66)
print(max(x))
print(min(x))
x=tuple(range(20))
print(x)
a=tuple(range(2))
print(a)
numbers=tuple(range(8))
print(numbers)
student=("ali","reza","javid","ali")
print(student.count("ali"))
nature=("forest","river","lake","see","see")
print(nature.count("see"))



        
