print("*** append() list ***")
a=["c#","java"]
d=list(range(5))
a.append(d)
print(a)
print("***range in list ***")
b=list(range(6))
print(b)
print("*** extend()***")
list1=["c#","java"]
list2=list(range(5))
list1.extend(list2)
print(list1)
print("***insert***")
a=["c++","java","python"]
a.insert(2,"c#")
print(a)
print("***pop()***")
pro=["c#","java","python"]
poped=pro.pop()
print(pro)
print("***remove()***")
pro=["c++","c","c#"]
pro.remove("c")
print(pro)
print("***reverse***")
software=["word","Excel","powerpoint"]
software.reverse()
print(software)
print("***sort***")
numbers=[30,10,50,20,40]
numbers.sort()
print(numbers)
print("***python collection(arrays) tuple***")
print("***data types tuple***")
fruits=("apple","banana","pineapple")
boolean=(True,False)
numbers=(10,20,30)
print(fruits)
print(type(fruits))
print(boolean)
print(type(boolean))
print(numbers)
print(type(numbers))
print(type(numbers))
print("***combine data type tuple***")
x=("color","apple",10,20,True,False)
print(x)
print(type(x))
print("***concatinate***")
number=(10,20,30)
colors=("blue","red")
print(number+colors)
print("*** immutable tuple***")
a=(10,20,30,10,10)
print(a)
print("***repetation tuple***")
number=(1,2,3)
print(number*2)
print("***none***")
a=()
print(a)

