print("***indexing tuple ***")
a=("a","b","c","d","e")
print(a[0])
print(a[2])
print(a[4])
print(a[-1])
print(a[-3])
print(a[:])
print(a[1:3])
print("***update tuple ***")
tuple1=("blue","green",1,2,True)
tuple1[1]==100
print(tuple1)
print("***delete tuple***")
##numbers=(10,20,30,40)
##del numbers[2]
##print(numbers)
##TypeError: 'tuple' object doesn't support item deletion
print("***search or find tuple ***")
hardware=("mouse","keyboard","monitor")
print("mouse" in hardware)
print("case" in hardware)
print("keyboard" not in hardware)
print("***len***")
c=("one","two","three","four")
print(len(c))
print("***max()tuple***")
numbers=(10,20,30,40,50)
print(max(numbers))
print(min(numbers))
print("***convers string to tuple ***")
a="python"
b=tuple(a)
print(b)
print("*** coun ***")
c=("c#","java","c#","python")
print(c.count("c#"))
print("***range in tuple***")
b=tuple(range(5))
print(b)
print("*** extend ***")
##a=("c#","java")
##b=tuple(range(5))
##a.extend(b)
##print(a)
##NameError: name 'number' is not defined. Did you mean: 'numbers'?
print("***insert()***")
##program=("c#","python","java")
##program.insert(2,"html")
##print(program)
print("***pop***")
a=("one","two","three")
##poped=a.pop()
print(a)

    
